// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelReservation.Core.Entities;

public partial class UserRoleMapping
{
    public int UserRoleMappingId { get; set; }

    public int UserId { get; set; }

    public int RoleId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UserRole Role { get; set; }

    public virtual User User { get; set; }
}