// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelReservation.Core.Entities;

public partial class UserRole
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<UserRoleMapping> UserRoleMappings { get; set; } = new List<UserRoleMapping>();
}